// <auto-generated />
using MicroserviceArchitecture.Services.EntityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroserviceArchitecture.Services.EntityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241211115828_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceArchitecture.Services.EntityAPI.Models.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("EntityId");

                    b.ToTable("Entitys");

                    b.HasData(
                        new
                        {
                            EntityId = 1,
                            Discount = 10,
                            DiscountPrice = 90.0,
                            EntityCode = "10%",
                            Price = 100.0
                        },
                        new
                        {
                            EntityId = 2,
                            Discount = 20,
                            DiscountPrice = 80.0,
                            EntityCode = "20%",
                            Price = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
